apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template: 
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: tjhirani/nodejs:latest
        ports:
        - containerPort: 3000