apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather
    app.kubernetes.io/instance: nodeapp
  name: nodeapp-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - image: 'tjhirani/nodejs:latest'
          name: weather
          ports:
            - containerPort: 3000

