apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nodeapp
  name: nodeapp-weather-service
  namespace: default
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 3000
  selector:
    app: weather
  type: LoadBalancer

